[net]
git-fetch-with-cli = true   # use the `git` executable for git operations

[target.x86_64-unknown-linux-gnu]
# linker = "/usr/bin/clang"
# rustflags = ["-C", "link-arg=--ld-path=/usr/bin/mold"]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=lld"]
